### ISSUE TITLE
Rich Text Editing

### ISSUE THREAD

**Issue by edeustace** [PieElements/pie-elements#22]
<img width="359" alt="screen shot 2017-08-15 at 12 37 43" src="https://user-images.githubusercontent.com/101623/29314614-a26504be-81b6-11e7-8404-e0020c2b7eea.png">

* [x] Formatting
* [x] Image Upload
* [x] Math formatting

**Comment by edeustace** [comment]
For math, I think our preference would be to use [katex](https://github.com/Khan/KaTeX), however we would have a fair bit of math content that is defined as mathml. To avoid using MathJax we'd have to convert the mathML into latex, before rendering on the client. It may be no harm to consider trialling converting all mathml content to Tex on the db and see how it renders.

**Comment by edeustace** [comment]
* https://efloti.github.io/draft-js-mathjax-plugin/
* https://github.com/draft-js-plugins/draft-js-plugins

**Comment by evaneus** [comment]
we're using mathquill in our current editing implementation right? and still using mathjax to render - although katex should be faster

**Comment by edeustace** [comment]
https://github.com/Khan/math-input - looks interesting
